[tool.black]
line-length = 119
target-version = ['py37']
include = '(crispy_forms)\/(.+)(py?$)'

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
mypy_path = "crispy_forms/"
no_implicit_optional = true
show_error_codes = true
warn_unreachable = true
warn_unused_ignores = true